package exceptionExample4;

public class Main {

	public static void main(String[] args) {
		Integer[] errorArray =new Integer[] {808,909,555,111,444};
		
		try {
			for(int i=0;i<errorArray.length;i++) {
				System.out.println("출력 : "+errorArray[i]);
			}
		}catch(Exception exception){
			
		}finally {
			System.out.println("무조건 출력");
		}

	}

}
